import type { Metadata } from "next";
import "./homeGlobals.css";
import Navbar from "@/components/client/Navbar";
import Navheader from "@/components/client/Navheader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        {/* <header>
          <Navheader />
          <Navbar />
        </header> */}
        {children}
      </body>
    </html>
  );
}
